backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

# Uncomment below to enable drafts
# publish_mode: editorial_workflow

media_folder: "static/img" # Media files will be stored in the repo under images/uploads

collections:
  - name: "pages"
    label: "Pages"
    files:
      - name: "jobs"
        label: "Jobs page"
        delete: false
        file: "src/site/pages/jobs.md"
        slug: "{{slug}}"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Cover", name: "cover", widget: "image", required: false }
          - { label: "Abstract", name: "abstract", widget: "markdown" }
          - { label: "Body", name: "body", widget: "markdown" }
